// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/features/pokemon_detail/detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_base_kit/core/domain/entity/evolution_chain_entity.dart'
    as _i4;
import 'package:flutter_base_kit/core/domain/entity/pokemon_entity.dart' as _i2;
import 'package:flutter_base_kit/core/domain/entity/pokemon_species_entity.dart'
    as _i3;
import 'package:flutter_base_kit/core/domain/repository/favorites_repository.dart'
    as _i9;
import 'package:flutter_base_kit/core/domain/usecase/get_evolution_chain_usecase.dart'
    as _i8;
import 'package:flutter_base_kit/core/domain/usecase/get_pokemon_by_id_usecase.dart'
    as _i5;
import 'package:flutter_base_kit/core/domain/usecase/get_pokemon_species_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemon_0 extends _i1.SmartFake implements _i2.Pokemon {
  _FakePokemon_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonSpecies_1 extends _i1.SmartFake
    implements _i3.PokemonSpecies {
  _FakePokemonSpecies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvolutionChain_2 extends _i1.SmartFake
    implements _i4.EvolutionChain {
  _FakeEvolutionChain_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPokemonByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonByIdUseCase extends _i1.Mock
    implements _i5.GetPokemonByIdUseCase {
  MockGetPokemonByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Pokemon> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i6.Future<_i2.Pokemon>.value(
              _FakePokemon_0(this, Invocation.method(#call, [id])),
            ),
          )
          as _i6.Future<_i2.Pokemon>);
}

/// A class which mocks [GetPokemonSpeciesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonSpeciesUseCase extends _i1.Mock
    implements _i7.GetPokemonSpeciesUseCase {
  MockGetPokemonSpeciesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.PokemonSpecies> call(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#call, [url]),
            returnValue: _i6.Future<_i3.PokemonSpecies>.value(
              _FakePokemonSpecies_1(this, Invocation.method(#call, [url])),
            ),
          )
          as _i6.Future<_i3.PokemonSpecies>);
}

/// A class which mocks [GetEvolutionChainUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEvolutionChainUseCase extends _i1.Mock
    implements _i8.GetEvolutionChainUseCase {
  MockGetEvolutionChainUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.EvolutionChain> call(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#call, [url]),
            returnValue: _i6.Future<_i4.EvolutionChain>.value(
              _FakeEvolutionChain_2(this, Invocation.method(#call, [url])),
            ),
          )
          as _i6.Future<_i4.EvolutionChain>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i9.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<Set<int>> get favoriteIdsStream =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteIdsStream),
            returnValue: _i6.Stream<Set<int>>.empty(),
          )
          as _i6.Stream<Set<int>>);

  @override
  _i6.Future<List<_i2.Pokemon>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i6.Future<List<_i2.Pokemon>>.value(<_i2.Pokemon>[]),
          )
          as _i6.Future<List<_i2.Pokemon>>);

  @override
  _i6.Future<void> addFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> toggleFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Set<int>> getFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIds, []),
            returnValue: _i6.Future<Set<int>>.value(<int>{}),
          )
          as _i6.Future<Set<int>>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
