// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_kit_auth/test/manager/auth_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_kit_auth/auth/domain/entity/auth_entity.dart' as _i6;
import 'package:flutter_kit_auth/auth/domain/entity/profile_entity.dart'
    as _i11;
import 'package:flutter_kit_auth/auth/domain/repository/auth_repository.dart'
    as _i2;
import 'package:flutter_kit_auth/auth/domain/usecase/apple_sign_in_usecase.dart'
    as _i15;
import 'package:flutter_kit_auth/auth/domain/usecase/google_sign_in_usecase.dart'
    as _i16;
import 'package:flutter_kit_auth/auth/domain/usecase/guest_sign_in_usecase.dart'
    as _i17;
import 'package:flutter_kit_auth/auth/domain/usecase/login_usecase.dart' as _i3;
import 'package:flutter_kit_auth/auth/domain/usecase/logout_usecase.dart'
    as _i13;
import 'package:flutter_kit_auth/auth/domain/usecase/me_usecase.dart' as _i10;
import 'package:flutter_kit_auth/auth/domain/usecase/refresh_usecase.dart'
    as _i14;
import 'package:flutter_kit_auth/auth/domain/usecase/register_usecase.dart'
    as _i9;
import 'package:flutter_kit_auth/auth/domain/usecase/update_profile_usecase.dart'
    as _i12;
import 'package:flutter_kit_auth/auth/token/token_store.dart' as _i18;
import 'package:flutter_kit_network/core/network/error/api_error.dart' as _i7;
import 'package:flutter_kit_network/core/utils/result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i9.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call({
    required String? email,
    required String? password,
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [], {
                      #email: email,
                      #password: password,
                      #firstName: firstName,
                      #lastName: lastName,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [MeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeUseCase extends _i1.Mock implements _i10.MeUseCase {
  MockMeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i11.Profile, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i12.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>> call(
    Map<String, dynamic>? patch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [patch]),
            returnValue:
                _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i11.Profile, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [patch]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i11.Profile, _i7.ApiError>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i13.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiError>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiError>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiError>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiError>>);
}

/// A class which mocks [RefreshUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshUseCase extends _i1.Mock implements _i14.RefreshUseCase {
  MockRefreshUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call(
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [refreshToken]),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [refreshToken]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [AppleSignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleSignInUseCase extends _i1.Mock
    implements _i15.AppleSignInUseCase {
  MockAppleSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call({
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#idToken: idToken}),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [], {#idToken: idToken}),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [GoogleSignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInUseCase extends _i1.Mock
    implements _i16.GoogleSignInUseCase {
  MockGoogleSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call({
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#idToken: idToken}),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, [], {#idToken: idToken}),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [GuestSignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestSignInUseCase extends _i1.Mock
    implements _i17.GuestSignInUseCase {
  MockGuestSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.AuthTokens, _i7.ApiError>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.AuthTokens, _i7.ApiError>>);
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i18.TokenStore {
  MockTokenStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.AuthTokens?> read() =>
      (super.noSuchMethod(
            Invocation.method(#read, []),
            returnValue: _i4.Future<_i6.AuthTokens?>.value(),
          )
          as _i4.Future<_i6.AuthTokens?>);

  @override
  _i4.Future<void> write(_i6.AuthTokens? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#write, [tokens]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> readAccess() =>
      (super.noSuchMethod(
            Invocation.method(#readAccess, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> readRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#readRefresh, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
