// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/features/movies/favorites_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_base_kit/core/domain/entity/movie.dart' as _i3;
import 'package:flutter_base_kit/core/local/favorites_store.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoritesStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesStore extends _i1.Mock implements _i2.FavoritesStore {
  MockFavoritesStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<int> get favoriteIds =>
      (super.noSuchMethod(Invocation.getter(#favoriteIds), returnValue: <int>{})
          as Set<int>);

  @override
  List<_i3.Movie> get favorites =>
      (super.noSuchMethod(
            Invocation.getter(#favorites),
            returnValue: <_i3.Movie>[],
          )
          as List<_i3.Movie>);

  @override
  bool isFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [id]),
            returnValue: false,
          )
          as bool);

  @override
  void toggle(_i3.Movie? movie) => super.noSuchMethod(
    Invocation.method(#toggle, [movie]),
    returnValueForMissingStub: null,
  );
}
