// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/core/data/repository/favorites_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_base_kit/core/data/datasource/favorites_local_datasource.dart'
    as _i2;
import 'package:flutter_base_kit/core/domain/entity/evolution_chain_entity.dart'
    as _i10;
import 'package:flutter_base_kit/core/domain/entity/pokemon_entity.dart' as _i6;
import 'package:flutter_base_kit/core/domain/entity/pokemon_species_entity.dart'
    as _i9;
import 'package:flutter_base_kit/core/domain/repository/pokemon_repository.dart'
    as _i4;
import 'package:flutter_kit_network/core/network/error/api_error.dart' as _i7;
import 'package:flutter_kit_network/core/utils/result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoritesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesLocalDataSource extends _i1.Mock
    implements _i2.FavoritesLocalDataSource {
  @override
  _i3.Future<Set<int>> getFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIds, []),
            returnValue: _i3.Future<Set<int>>.value(<int>{}),
            returnValueForMissingStub: _i3.Future<Set<int>>.value(<int>{}),
          )
          as _i3.Future<Set<int>>);

  @override
  _i3.Future<void> addFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i4.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>> page(
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#page, [offset]),
            returnValue:
                _i3.Future<
                  _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                  >(this, Invocation.method(#page, [offset])),
                ),
          )
          as _i3.Future<
            _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
          >);

  @override
  _i3.Future<_i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>>
  pageWithSize(int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageWithSize, [size, offset]),
            returnValue:
                _i3.Future<
                  _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                  >(this, Invocation.method(#pageWithSize, [size, offset])),
                ),
          )
          as _i3.Future<
            _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
          >);

  @override
  _i3.Future<_i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>>
  pageByType(String? type, int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageByType, [type, size, offset]),
            returnValue:
                _i3.Future<
                  _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                  >(this, Invocation.method(#pageByType, [type, size, offset])),
                ),
          )
          as _i3.Future<
            _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
          >);

  @override
  _i3.Future<_i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>>
  pageSearch(String? query, int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageSearch, [query, size, offset]),
            returnValue:
                _i3.Future<
                  _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
                  >(
                    this,
                    Invocation.method(#pageSearch, [query, size, offset]),
                  ),
                ),
          )
          as _i3.Future<
            _i5.Result<(List<_i6.Pokemon>, bool, int), _i7.ApiError>
          >);

  @override
  _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.Pokemon, _i7.ApiError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>>);

  @override
  _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>> getByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getByName, [name]),
            returnValue:
                _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.Pokemon, _i7.ApiError>>(
                    this,
                    Invocation.method(#getByName, [name]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i6.Pokemon, _i7.ApiError>>);

  @override
  _i3.Future<_i5.Result<_i9.PokemonSpecies, _i7.ApiError>> getSpecies(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecies, [url]),
            returnValue:
                _i3.Future<_i5.Result<_i9.PokemonSpecies, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i9.PokemonSpecies, _i7.ApiError>>(
                    this,
                    Invocation.method(#getSpecies, [url]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i9.PokemonSpecies, _i7.ApiError>>);

  @override
  _i3.Future<_i5.Result<_i10.EvolutionChain, _i7.ApiError>> getEvolutionChain(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvolutionChain, [url]),
            returnValue:
                _i3.Future<_i5.Result<_i10.EvolutionChain, _i7.ApiError>>.value(
                  _i8.dummyValue<_i5.Result<_i10.EvolutionChain, _i7.ApiError>>(
                    this,
                    Invocation.method(#getEvolutionChain, [url]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i10.EvolutionChain, _i7.ApiError>>);
}
