// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/core/data/repository/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_base_kit/core/data/datasource/pokemon_remote_datasource.dart'
    as _i5;
import 'package:flutter_base_kit/core/domain/entity/evolution_chain_entity.dart'
    as _i4;
import 'package:flutter_base_kit/core/domain/entity/pokemon_brief_entity.dart'
    as _i7;
import 'package:flutter_base_kit/core/domain/entity/pokemon_entity.dart' as _i2;
import 'package:flutter_base_kit/core/domain/entity/pokemon_species_entity.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemon_0 extends _i1.SmartFake implements _i2.Pokemon {
  _FakePokemon_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonSpecies_1 extends _i1.SmartFake
    implements _i3.PokemonSpecies {
  _FakePokemonSpecies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvolutionChain_2 extends _i1.SmartFake
    implements _i4.EvolutionChain {
  _FakeEvolutionChain_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteDataSource extends _i1.Mock
    implements _i5.PokemonRemoteDataSource {
  MockPokemonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.PokemonBrief>> listPokemon({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listPokemon, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i7.PokemonBrief>>.value(
              <_i7.PokemonBrief>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonBrief>>);

  @override
  _i6.Future<List<_i7.PokemonBrief>> getAllBriefs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBriefs, []),
            returnValue: _i6.Future<List<_i7.PokemonBrief>>.value(
              <_i7.PokemonBrief>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonBrief>>);

  @override
  _i6.Future<_i2.Pokemon> getDetailByName(
    String? name, {
    bool? includeMoves = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDetailByName,
              [name],
              {#includeMoves: includeMoves},
            ),
            returnValue: _i6.Future<_i2.Pokemon>.value(
              _FakePokemon_0(
                this,
                Invocation.method(
                  #getDetailByName,
                  [name],
                  {#includeMoves: includeMoves},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Pokemon>);

  @override
  _i6.Future<_i2.Pokemon> getDetailByUrl(
    String? url, {
    bool? includeMoves = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDetailByUrl,
              [url],
              {#includeMoves: includeMoves},
            ),
            returnValue: _i6.Future<_i2.Pokemon>.value(
              _FakePokemon_0(
                this,
                Invocation.method(
                  #getDetailByUrl,
                  [url],
                  {#includeMoves: includeMoves},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Pokemon>);

  @override
  _i6.Future<List<_i7.PokemonBrief>> filterByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#filterByType, [type]),
            returnValue: _i6.Future<List<_i7.PokemonBrief>>.value(
              <_i7.PokemonBrief>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonBrief>>);

  @override
  _i6.Future<List<_i7.PokemonBrief>> searchPokemon(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPokemon, [query]),
            returnValue: _i6.Future<List<_i7.PokemonBrief>>.value(
              <_i7.PokemonBrief>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonBrief>>);

  @override
  _i6.Future<_i3.PokemonSpecies> getSpeciesByUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getSpeciesByUrl, [url]),
            returnValue: _i6.Future<_i3.PokemonSpecies>.value(
              _FakePokemonSpecies_1(
                this,
                Invocation.method(#getSpeciesByUrl, [url]),
              ),
            ),
          )
          as _i6.Future<_i3.PokemonSpecies>);

  @override
  _i6.Future<_i4.EvolutionChain> getEvolutionChain(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getEvolutionChain, [url]),
            returnValue: _i6.Future<_i4.EvolutionChain>.value(
              _FakeEvolutionChain_2(
                this,
                Invocation.method(#getEvolutionChain, [url]),
              ),
            ),
          )
          as _i6.Future<_i4.EvolutionChain>);
}
