// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/core/domain/usecase/pokemon_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_base_kit/core/domain/entity/evolution_chain_entity.dart'
    as _i9;
import 'package:flutter_base_kit/core/domain/entity/pokemon_entity.dart' as _i5;
import 'package:flutter_base_kit/core/domain/entity/pokemon_species_entity.dart'
    as _i8;
import 'package:flutter_base_kit/core/domain/repository/pokemon_repository.dart'
    as _i2;
import 'package:flutter_kit_network/core/network/error/api_error.dart' as _i6;
import 'package:flutter_kit_network/core/utils/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i2.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>> page(
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#page, [offset]),
            returnValue:
                _i3.Future<
                  _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                  >(this, Invocation.method(#page, [offset])),
                ),
          )
          as _i3.Future<
            _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
          >);

  @override
  _i3.Future<_i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>>
  pageWithSize(int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageWithSize, [size, offset]),
            returnValue:
                _i3.Future<
                  _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                  >(this, Invocation.method(#pageWithSize, [size, offset])),
                ),
          )
          as _i3.Future<
            _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
          >);

  @override
  _i3.Future<_i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>>
  pageByType(String? type, int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageByType, [type, size, offset]),
            returnValue:
                _i3.Future<
                  _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                  >(this, Invocation.method(#pageByType, [type, size, offset])),
                ),
          )
          as _i3.Future<
            _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
          >);

  @override
  _i3.Future<_i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>>
  pageSearch(String? query, int? size, int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#pageSearch, [query, size, offset]),
            returnValue:
                _i3.Future<
                  _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
                  >(
                    this,
                    Invocation.method(#pageSearch, [query, size, offset]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Result<(List<_i5.Pokemon>, bool, int), _i6.ApiError>
          >);

  @override
  _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Pokemon, _i6.ApiError>>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>> getByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getByName, [name]),
            returnValue:
                _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>>.value(
                  _i7.dummyValue<_i4.Result<_i5.Pokemon, _i6.ApiError>>(
                    this,
                    Invocation.method(#getByName, [name]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.Pokemon, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i8.PokemonSpecies, _i6.ApiError>> getSpecies(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecies, [url]),
            returnValue:
                _i3.Future<_i4.Result<_i8.PokemonSpecies, _i6.ApiError>>.value(
                  _i7.dummyValue<_i4.Result<_i8.PokemonSpecies, _i6.ApiError>>(
                    this,
                    Invocation.method(#getSpecies, [url]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.PokemonSpecies, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i9.EvolutionChain, _i6.ApiError>> getEvolutionChain(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvolutionChain, [url]),
            returnValue:
                _i3.Future<_i4.Result<_i9.EvolutionChain, _i6.ApiError>>.value(
                  _i7.dummyValue<_i4.Result<_i9.EvolutionChain, _i6.ApiError>>(
                    this,
                    Invocation.method(#getEvolutionChain, [url]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.EvolutionChain, _i6.ApiError>>);
}
