// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_kit_auth/test/repository/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i7;
import 'package:flutter_kit_auth/auth/data/dto/auth_dto.dart' as _i5;
import 'package:flutter_kit_auth/auth/data/remote/auth_remote_datasource.dart'
    as _i2;
import 'package:flutter_kit_network/core/network/error/api_error.dart' as _i6;
import 'package:flutter_kit_network/core/utils/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> login(
    _i5.LoginRequestDto? dto, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [dto], {#cancelToken: cancelToken}),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #login,
                      [dto],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> register(
    _i5.RegisterRequestDto? dto, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [dto], {#cancelToken: cancelToken}),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #register,
                      [dto],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> refresh(
    String? refreshToken, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #refresh,
              [refreshToken],
              {#cancelToken: cancelToken},
            ),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #refresh,
                      [refreshToken],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>> me({
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#me, [], {#cancelToken: cancelToken}),
            returnValue:
                _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.ProfileDto, _i6.ApiError>>(
                    this,
                    Invocation.method(#me, [], {#cancelToken: cancelToken}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>> updateProfile(
    Map<String, dynamic>? patch, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfile,
              [patch],
              {#cancelToken: cancelToken},
            ),
            returnValue:
                _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.ProfileDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #updateProfile,
                      [patch],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.ProfileDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<void, _i6.ApiError>> logout({
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#cancelToken: cancelToken}),
            returnValue: _i3.Future<_i4.Result<void, _i6.ApiError>>.value(
              _i8.dummyValue<_i4.Result<void, _i6.ApiError>>(
                this,
                Invocation.method(#logout, [], {#cancelToken: cancelToken}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> appleSignIn(
    _i5.SocialAuthRequestDto? dto, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appleSignIn, [dto], {#cancelToken: cancelToken}),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #appleSignIn,
                      [dto],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> googleSignIn(
    _i5.SocialAuthRequestDto? dto, {
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #googleSignIn,
              [dto],
              {#cancelToken: cancelToken},
            ),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(
                      #googleSignIn,
                      [dto],
                      {#cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);

  @override
  _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>> guestSignIn({
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#guestSignIn, [], {#cancelToken: cancelToken}),
            returnValue:
                _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>.value(
                  _i8.dummyValue<_i4.Result<_i5.TokensDto, _i6.ApiError>>(
                    this,
                    Invocation.method(#guestSignIn, [], {
                      #cancelToken: cancelToken,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.TokensDto, _i6.ApiError>>);
}
