// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/features/pokemon_home/pokemon_home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_base_kit/core/domain/entity/pokemon_entity.dart' as _i4;
import 'package:flutter_base_kit/core/domain/repository/favorites_repository.dart'
    as _i7;
import 'package:flutter_base_kit/core/domain/usecase/filter_pokemon_by_type_usecase.dart'
    as _i5;
import 'package:flutter_base_kit/core/domain/usecase/get_pokemon_page_usecase.dart'
    as _i2;
import 'package:flutter_base_kit/core/domain/usecase/search_pokemon_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetPokemonPageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonPageUseCase extends _i1.Mock
    implements _i2.GetPokemonPageUseCase {
  MockGetPokemonPageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(List<_i4.Pokemon>, bool, int)> call({
    required int? size,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#size: size, #offset: offset}),
            returnValue: _i3.Future<(List<_i4.Pokemon>, bool, int)>.value((
              <_i4.Pokemon>[],
              false,
              0,
            )),
          )
          as _i3.Future<(List<_i4.Pokemon>, bool, int)>);
}

/// A class which mocks [FilterPokemonByTypeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterPokemonByTypeUseCase extends _i1.Mock
    implements _i5.FilterPokemonByTypeUseCase {
  MockFilterPokemonByTypeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(List<_i4.Pokemon>, bool, int)> call({
    required String? type,
    required int? size,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #type: type,
              #size: size,
              #offset: offset,
            }),
            returnValue: _i3.Future<(List<_i4.Pokemon>, bool, int)>.value((
              <_i4.Pokemon>[],
              false,
              0,
            )),
          )
          as _i3.Future<(List<_i4.Pokemon>, bool, int)>);
}

/// A class which mocks [SearchPokemonUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPokemonUseCase extends _i1.Mock
    implements _i6.SearchPokemonUseCase {
  MockSearchPokemonUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(List<_i4.Pokemon>, bool, int)> call({
    required String? query,
    required int? size,
    required int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #query: query,
              #size: size,
              #offset: offset,
            }),
            returnValue: _i3.Future<(List<_i4.Pokemon>, bool, int)>.value((
              <_i4.Pokemon>[],
              false,
              0,
            )),
          )
          as _i3.Future<(List<_i4.Pokemon>, bool, int)>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i7.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Set<int>> get favoriteIdsStream =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteIdsStream),
            returnValue: _i3.Stream<Set<int>>.empty(),
          )
          as _i3.Stream<Set<int>>);

  @override
  _i3.Future<List<_i4.Pokemon>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i3.Future<List<_i4.Pokemon>>.value(<_i4.Pokemon>[]),
          )
          as _i3.Future<List<_i4.Pokemon>>);

  @override
  _i3.Future<void> addFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleFavorite(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Set<int>> getFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIds, []),
            returnValue: _i3.Future<Set<int>>.value(<int>{}),
          )
          as _i3.Future<Set<int>>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
